name: actions-usage

on:
  workflow_dispatch:

jobs:
  actions-usage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: gh-actuse
      run: |
        gh extension install geoffreywiseman/gh-actuse
        gh actuse
      env:
        GH_TOKEN: ${{ github.token }}
