# This is a basic workflow that is manually triggered

name: docker-spark

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    container: bitnami/spark
    env:
      SPARK_MODE: master
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: spark --help
