name: generate-license
 
on:
  workflow_dispatch:

jobs:
  gen-license:
    runs-on: ubuntu-latest

    steps:
    
    - name: gen-license
      run: |
        gh extension install mislav/gh-license
        gh license
      env: 
       GH_TOKEN: ${{ github.token }}
