name: gh-runner-check

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: servicechecks
      run: |
        cat ~/actions-runner/.service
        systemctl --type=service
        sudo systemctl is-active docker.service
