# Further improvements - setup uv action, ruff action
# https://docs.astral.sh/uv/guides/integration/github/
# https://github.com/chartboost/ruff-action
# Further Improvements: file extension, path filtering
# https://github.com/dorny/paths-filter

name: 🐶 ruff

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
      - '!release*/*'
    tags:        
      - '!v*'
  pull_request:
    branches:
      - "*"
      - '!release*/*'

permissions:
  contents: read

jobs:

  ruff-bot:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.12"
    
        - name: Install ruff
          run: pip install ruff

        # The working folder should be set to the location of pyproject.toml
        # Settings for ruff defined in pyproject.toml  
        - name: Run ruff format and fix
          continue-on-error: true
          run: |
              ruff format .
              ruff check . --fix
              # This should have a toggle for workflow dispatch
              ruff check . --fix --unsafe-fixes

        - name: Check for changes
          id: check_changes
          run: |
            if [ -n "$(git diff)" ]; then
              echo "::set-output name=changed::true"
            else
              echo "::set-output name=changed::false"
            fi
          continue-on-error: true

        # Placeholder - checking for file changes
        # - shell: pwsh
        #   id: check_file_changed
        #   run: |
        #     # Diff HEAD with the previous commit
        #     $diff = git diff --name-only HEAD^ HEAD
    
        #     # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        #     $SourceDiff = $diff | Where-Object { $_ -match '^docs/' -or $_ -match '.md$' }
        #     $HasDiff = $SourceDiff.Length -gt 0
    
        #     # Set the output named "docs_changed"
        #     Write-Host "::set-output name=docs_changed::$HasDiff"

        # # Run the step only with "docs_changed" equals "True"
        # - shell: pwsh
        #   # steps.<step_id>.outputs.<output name>
        #   if: steps.check_file_changed.outputs.docs_changed == 'True'
        #   run: echo publish docs
      
        # Customize the user name and commit message, and can add an email such as Github Actions email
        - name: Set up Git and Commit Changes
          run: |
            if [ "${{ steps.check_changes.outputs.changed }}" == "true" ]; then
              git config --local user.name "ruff [BOT]"
              git config --local user.email "asears@users.noreply.github.com"
              git add .
              git commit -m "ruff ruff 🐕"
              git push
        fi

        # # TODO(AS): Comment that the PR was fixed with ruff, only in a pr.
        # - uses: actions/github-script@v7
        #   with:
        #     script: |
        #       if [ "${{ steps.check_changes.outputs.changed }}" == "true" ]; then
        #         github.rest.issues.createComment({
        #           issue_number: context.issue.number,
        #           owner: context.repo.owner,
        #           repo: context.repo.repo,
        #           body: 'ruff ruff 🐕'
        #         })
        #       fi

  # # Run the job only with "docs_changed" equals "True"
  # conditional_job:
  #   runs-on: 'ubuntu-20.04'
  #   needs: [ conditional_job_check_files ]
  #   if: needs.conditional_job_check_files.outputs.docs_changed == 'True'
  #   steps:
  #   - shell: pwsh
  #     run: echo publish docs
