name: ruff

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:

  ruff-bot:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.12"
    
        - name: Install ruff
          run: pip install ruff

        # The working folder should be set to the location of pyproject.toml
        # Settings for ruff defined in pyproject.toml  
        - name: Run ruff format and fix
          continue-on-error: true
          run: |
              ruff format .
              ruff --fix .
              # This should have a toggle for workflow dispatch
              ruff --fix --unsafe-fixes .

        - name: Check for changes
          id: check_changes
          run: |
            if [ -n "$(git diff)" ]; then
              echo "::set-output name=changed::true"
            else
              echo "::set-output name=changed::false"
            fi
          continue-on-error: true
  
        # Optionally, customize the user name and commit message, and can add an email as well such as Github Actions' email
        - name: Set up Git and Commit Changes
          run: |
            if [ "${{ steps.check_changes.outputs.changed }}" == "true" ]; then
              git config --local user.name "ruff [BOT]"
              git add .
              git commit -m "ruff ruff 🐕"
              git push
            fi
