name: script runner
on: workflow_dispatch

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('/.github/scripts/script.js')
            console.log(script({github, context}))

      - uses: actions/github-script@v7
      env:
          SHA: '${{env.parentSHA}}'
      with:
          script: |
            const script = require('.github/scripts/async_script.js')
            await script({github, context, core})