name: test-ci

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:

  test-ci:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          os: [Ubuntu]
          python_version: ["3.12"]
      permissions:
        contents: write
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Install poetry
          run: |
            pipx install poetry
            poetry --version
          
        - name: Set up Python
          id: setup-python
          uses: actions/setup-python@v4
          with:
            # python-version-file: '.python-version'
            # python-version-file: 'pyproject.toml'
            python-version: "${{ matrix.python_version }}"
            allow-prereleases: true
            update-environment: true
            cache: 'poetry'
            # cache-dependency-path: setup.py
        
        - run: |
              echo '${{ steps.setup-python.outputs.python-version }}'
              echo '${{ steps.setup-python.outputs.python-path }}'
        
        # - run: poetry install

        - name: Install pytest and ruff
          run: |
            pip install pytest pytest-cov pytest-mock ruff
            pytest --version
            ruff --version

        - name: Run ruff
          continue-on-error: true
          run: |
              ruff .

        - name: Run ruff format
          continue-on-error: true
          run: |
              ruff format . 
        
        - name: Run pytest
          continue-on-error: false
          run: |
              pytest .
              # pipx run nox --error-on-missing-interpreters -s tests-${{ matrix.python_version }}
              # poetry run pytest
        # TODO(AS): if tests succeed and ruff failed, format and fix and run tests again
        # - uses: actions/github-script@v7
        #   with:
        #     retries: 0
        #     result-encoding: string
        #     retry-exempt-status-codes: 400,401,403,404,422
        #     script: |
        #       if [ "${{ steps.check_changes.outputs.changed }}" == "true" ]; then
        #         github.rest.actions.createWorkflowDispatch({
        #           owner: owner,
        #           repo: repo,
        #           workflow_id: workflow_id,
        #           ref: ref
        #         })
        #       fi
        # TODO(AS): If tests fail, then rollback the ruff commit.
        # - name: Run pytest
        #   continue-on-error: false
        #   run: |
        #       pytest .
        # Debugging
        - name: View context attributes
          uses: actions/github-script@v7
          with:
            script: console.log(context)
